apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-staging
  namespace: argocd

spec:
  project: default
  source:
    repoURL: 'https://github.com/florianpialoux/argocd-demo.git'
    path: manifest
    targetRevision: HEAD
  destination:
    namespace: default
    name: cluster-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
