apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8085
    targetPort: 3000
    nodePort: 32439
    protocol: TCP
  selector:
    app: grafana
