apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
spec:
  ports:
  - nodePort: 32439
    port: 3000
    protocol: TCP
  selector:
    app: grafana
  type: NodePort
